return {
  -- add any tools you want to have installed below
  {
    "mason-org/mason.nvim",
    opts = {
      ensure_installed = {
        "stylua",
        "shellcheck",
        "shfmt",
        "flake8",
        "checkstyle",
        "clang-format",
        "clangd",
        "codelldb",
        "html-lsp",
        "prettier",
        "yaml-language-server",
        "rubocop",
        "gitlab-ci-ls",
        "prisma-language-server",
        "ruff",
        "gh-actions-language-server",
        "arduino-language-server",
        "biome",
        "css-lsp",
        "eslint-lsp",
        "json-lsp",
        "lua-language-server",
        "marksman",
        "mdx-analyzer",
        "pyright",
        "ruby-lsp",
        "rust-analyzer",
        "svelte-language-server",
        "tailwindcss-language-server",
        "taplo",
        "vtsls",
      },
    },
  },
}
