return {
  {
    "nvim-treesitter/nvim-treesitter",
    opts = {
      matchup = {
        enable = true,
      },
      ensure_installed = {
        "bash",
        "html",
        "javascript",
        "prisma",
        "csv",
        "dart",
        "graphql",
        "http",
        "java",
        "json",
        "rust",
        "toml",
        "cpp",
        "gitignore",
        "gitcommit",
        "svelte",
        "scss",
        "css",
        "lua",
        "markdown",
        "markdown_inline",
        "python",
        "query",
        "regex",
        "tsx",
        "typescript",
        "vim",
        "xml",
        "yaml",
        "hyprlang",
        "hurl",
        "angular",
      },
    },
  },
}
